name: Model Drift Check on Live Data Updates

on:
  push:
    branches:
      - live-data-branch

jobs:
  trigger-from-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install deepchecks pandas scikit-learn

      - name: Load latest live data from live-data-branch
        run: |
          echo "📥 Copying latest live data from live-data-branch..."
          git fetch origin live-data-branch
          git checkout --force origin/live-data-branch -- live_inputs.csv

      - name: Drift Check
        run: |
          python drift_check.py
          
      - name: Upload Drift Report
        uses: actions/upload-artifact@v4
        with:
          name: drift-report
          path: drift_report.html
